name: run tests and linter
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Poetry install
        run: curl -sSL https://install.python-poetry.org | python3 -
      - uses: actions/checkout@v3
      - run: poetry install
      - name: linter
        run: make lint
      - name: coverage & tests
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: make test